services:
  local-pgbouncer:
    image: 127.0.0.1:5000/pgbouncer:42363893e2806b6263b96dd8
    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: any
    networks:
      - noops-local
    env_file:
      - /Users/odu/Documents/alien/code-innate/personal/no-oops-ops/examples/paas/.noops/state/apps/pgbouncer/local/.env
    entrypoint:
      - /bin/sh
      - /bootstrap.sh
    command:
      - /entrypoint.sh
      - /usr/bin/pgbouncer
      - /etc/pgbouncer/pgbouncer.ini
    environment:
      NOOPS_SECRET_MAPPINGS: DB_USER=/run/secrets/DB_USER,DB_PASSWORD=/run/secrets/DB_PASSWORD
      DB_USER_FILE: /run/secrets/DB_USER
      DB_PASSWORD_FILE: /run/secrets/DB_PASSWORD
    secrets:
      - source: noops_local_POSTGRES_USER_SECRET_v1
        target: DB_USER
        mode: 0444
      - source: noops_local_POSTGRES_PASSWORD_SECRET_v1
        target: DB_PASSWORD
        mode: 0444
volumes:
  postgres_data:
networks:
  noops-local:
    external: true
secrets:
  noops_local_POSTGRES_USER_SECRET_v1:
    external: true
  noops_local_POSTGRES_PASSWORD_SECRET_v1:
    external: true

