services:
  neo4j:
    image: "neo4j:5-enterprise"
    ports:
      - target: 7474
        published: 7474
        protocol: tcp
        mode: host
      - target: 7687
        published: 7687
        protocol: tcp
        mode: host
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474/" ]
      interval: 15s
      timeout: 10s
      start_period: 60s
      retries: 5
    volumes:
      - "neo4j_data:/data"
    x-noops:
      rollout:
        convergence_timeout: 4m
        monitor: 2m
      ingress:
        blue_green: false
      env:
        file: env.yml
        secrets:
          resolution: env
          resolvable:
            - NEO4J_AUTH
volumes:
  neo4j_data:
