services:
  lango:
    image: lango-service
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: [ CMD, curl, -f, http://localhost:8080/lango/liveness ]
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
    x-noops:
      build:
        source:
          git:
            url: https://github.com/example/lango.git
            environments:
              dev:
                ref: isolate-build
                secret: mysecret
              staging:
                ref: main
                secret: github-readonly
              prod:
                ref: refs/tags/v1.0.0
                secret: github-readonly
      service:
        internal_port: 8080
      expose:
        enabled: true
        blue_green: true
        domain: lango.example.com
        path_prefix: /
      env:
        file: lango.env.yml
        secrets:
          resolution: env
          resolvable: [ REDIS_PASSWORD, AUTH_SERVER_API_CLIENT_SECRET ]
